# Dependabot configuration for automatic dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    assignees:
      - "rootkitoriginal"
    labels:
      - "dependencies"
      - "python"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group minor and patch updates together
    groups:
      fastapi-dependencies:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "pydantic*"
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "flake8"
          - "isort"
          - "mypy"
          - "pre-commit"
      security-dependencies:
        patterns:
          - "cryptography*"
          - "python-jose*"
          - "passlib*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    assignees:
      - "rootkitoriginal"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
