name: Docker Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: xpagbank:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test Docker image
      run: |
        docker run --rm -d --name xpagbank-test -p 8000:8000 xpagbank:test
        sleep 10
        
        # Wait for service to be ready
        for i in {1..30}; do
          if curl -f http://localhost:8000/health; then
            echo "✓ Health check passed"
            docker stop xpagbank-test
            exit 0
          fi
          echo "Waiting for service... ($i/30)"
          sleep 2
        done
        
        echo "❌ Health check failed"
        docker logs xpagbank-test
        docker stop xpagbank-test
        exit 1
