name: Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov httpx
    
    - name: Install Playwright browsers
      run: playwright install chromium --with-deps
    
    - name: Run tests (if test directory exists)
      run: |
        if [ -d "tests" ]; then
          pytest tests/ -v --cov=app --cov-report=term-missing
        else
          echo "No tests directory found - skipping tests"
          echo "Tests will be added in future iterations"
        fi
    
    - name: Health check test
      run: |
        python -c "
        import sys
        sys.path.insert(0, '.')
        from app.main import app
        from app.core.config import get_settings
        settings = get_settings()
        print('✓ Application imports successfully')
        print(f'✓ Settings loaded: clientes_dir={settings.clientes_dir}')
        "
